name: Keep Codespace Active and Start Minecraft Server

on:
  schedule:
    - cron: "0 */3 * * *"  # Every 3 hours

jobs:
  keep_alive_and_start:
    runs-on: ubuntu-latest

    steps:
      - name: Start Codespace if Inactive
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          codespace_name="foul-hex-wpjp7x9x6gvf59pv"  # Your Codespace name
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/codespaces/$codespace_name/start

      - name: Run Minecraft Server and BungeeCord in Background
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Start the Minecraft server
          nohup bash -c "cd server && sudo java -jar server.jar" &

          # Start BungeeCord
          nohup bash -c "cd bungee && sudo java -jar bungee.jar" &
