name: Keep Codespace Active

on:
  schedule:
    - cron: "0 */3 * * *"  # Every 3 hours

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Start Codespace if Inactive
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          codespace_name="foul-hex-wpjp7x9x6gvf59pv"  # Using your Codespace name
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/codespaces/$codespace_name/start
